// Length added to hilt (inches), from Vire Saber Builder catalog.
// Integer values >= 20 on non-blade parts were stored as hundredths (98 -> 0.98).
export const LENGTH_BY_SLUG = {
  "1-5-extension": 1.5,
  "2-5-kam-extension": 2.55,
  "7-8-blade": 1,
  "a-emitter-guardian-black": 3.1,
  "admiral-emitter": 3.1,
  "admiral-grip": 4.25,
  "android-emitter-switch-combo": 5.17,
  "android-grip": 4.91,
  "apoc-emitter-switch-solid-combo": 5.15,
  "apoc-grip": 4.92,
  "apoc-pommel": 0.74,
  "aussabers-emitter-cap-v1": 0.4,
  "aussabers-incendius-double-female-coupler": 1.57,
  "aussabers-invictus-pommel": 0.94,
  "aussabers-pixel-thin-neck-adapter": 1,
  "av-wan": 1.44,
  "avatar-band": 1,
  "banded-accent-extension": 7,
  "baselit-single-led-cross-blade-switch": 4.78,
  "beacon-emitter": 3.07,
  "beacon-pommel": 1.15,
  "beacon-switch": 2.87,
  "bermuda-emitter": 5.08,
  "bermuda-grip": 3.94,
  "bermuda-switch": 1.96,
  "bishop-emitter": 3.4,
  "bishop-grip": 3.8,
  "build-a-cross-blade": 3.4,
  "c-guardian-handle": 4.21,
  "capsule-pommel": 1.8,
  "castille-pommel": 1,
  "claw-grip": 4.6,
  "claw-sphere-pommel": 1.13,
  "clutch-emitter-switch-combo": 4.6,
  "clutch-grip": 4.32,
  "consular-grip": 4.69,
  "consular-pommel": 1.77,
  "consular-shroud": 2.35,
  "consular-switch": 3.03,
  "convergence-switch": 2.36,
  "copy-of-avatar-band": 1,
  "copy-of-claw-grip": 4.12,
  "copy-of-inquisitor-grip": 4.46,
  "copy-of-spire-emitter-and-choke": 3.82,
  "cyborg-emitter": 3.15,
  "cyborg-grip": 4.92,
  "cyborg-switch": 2.3,
  "d-guardian-double-connector-pommel": 0.58,
  "danger-noodle-light-whip": 44.5,
  "dark-crown-emitter": 3.8,
  "dark-crystal-chamber": 3.39,
  "dark-rev-emitter-switch-combo": 6,
  "dark-rev-grip": 4.46,
  "dark-rev-pommel": 0.93,
  "darkthorn-pommel": 1.2,
  "day-blade": 36,
  "diamondback-emitter": 4.3,
  "diamondback-jr-emitter": 3.27,
  "disk-pommel": 0.32,
  "double-male-coupler": 0.38,
  "durendal-emitter": 2.42,
  "durendal-grip": 3.48,
  "durendal-pommel": 1.28,
  "durendal-switch": 2.85,
  "equinox-emitter": 3.1,
  "etched-vire-tsuba": 0.35,
  "executioner-emitter-switch": 6.8,
  "executioner-grip": 3.74,
  "executioner-pommel": 0.96,
  "executioner-shroud-sleeve": 5.58,
  "fallen-ember-emitter": 3.26,
  "fallen-ember-grip": 4.93,
  "fallen-ember-pommel": 1.73,
  "fallen-ember-shroud": 4.19,
  "fallen-ember-switch": 2.83,
  "fang-emitter": 3.4,
  "fang-grip": 4.2,
  "female-to-male-vhc-stealth-adapter": 0,
  "gatekeeper-emitter": 4.1,
  "gill-extension": 1,
  "grappler-grip-with-covertec-wheel": 5.1,
  "grappler-pommel": 0.32,
  "grip-extension": 2,
  "grip-sleeves": 5.1,
  "guardian-hollow-female-female-coupler": 0.66,
  "guardian-switch-usb-c": 2,
  "halcyon-choke": 1.7,
  "halcyon-emitter-1": 2.17,
  "halcyon-pommel": 1.84,
  "halcyon-switch": 5.08,
  "heavy-blade": 1,
  "helix-emitter": 3.34,
  "helix-grip": 3.92,
  "helix-pommel": 1.17,
  "helix-switch": 2.36,
  "imperial-extension": 3.01,
  "imperial-pommel": 2.41,
  "infiltrator-emitter": 3.03,
  "infiltrator-pommel": 1.5,
  "infiltrator-switch-grip": 6.2,
  "inquisitor-grip": 4.86,
  "interceptor-emitter-switch-solid-combo": 5.17,
  "interceptor-grip": 4.73,
  "interceptor-pommel": 0.81,
  "ion-grip": 4.93,
  "ion-pommel": 1,
  "jade-grip": 4.93,
  "jade-grip-scratch-dent": 4.93,
  "jester-emitter": 3.8,
  "kam-pommel": 1.17,
  "knight-emitter": 4.2,
  "lotus-emitter": 3.12,
  "lotus-grip": 4.9,
  "lotus-pommel": 1.13,
  "mantis-emitter": 2.72,
  "mantis-emitter-switch-combo": 6.5,
  "mantis-grip": 5.5,
  "maul-shroud": 2,
  "menace-emitter": 2.7,
  "menace-pommel": 1.5,
  "menace-switch-grip-combo": 7.2,
  "mentor-grip": 4.9,
  "mentor-switch-double-male-threads": 2.3,
  "mini-tsuba": 0.59,
  "modular-crystal-chamber": 2.3,
  "monarch-emitter": 3,
  "monarch-pommel": 1.1,
  "nostalgia-blade": 13,
  "nova-emitter-switch": 5.06,
  "nova-grip": 5.11,
  "nova-pommel": 0.88,
  "odyssey-emitter": 2.51,
  "odyssey-grip": 4.33,
  "odyssey-pommel": 0.99,
  "oracle-emitter": 3.69,
  "oracle-grip": 4.3,
  "oracle-pommel": 1.3,
  "oracle-switch": 2.44,
  "oracle-switch-type-c-mod": 2.44,
  "padawan-grip": 4.3,
  "pathfinder-switch-emitter-solid-combo": 5.16,
  "pax-emitter": 1.2,
  "pax-pommel-frosted": 0.82,
  "phantom-grip": 4.9,
  "phoenix-emitter": 4.1,
  "phoenix-grip": 3.82,
  "phoenix-pommel": 1.76,
  "pike-grip": 52,
  "pilot-emitter": 2.55,
  "pilot-grip": 4.33,
  "pilot-pommel": 0.62,
  "pixel-to-base-lit-rgb-adapter": 0.55,
  "raider-emitter": 2.56,
  "raider-grip": 4.13,
  "raider-pommel": 0.98,
  "ranger-extension": 3.54,
  "rev-double-male-coupler": 0.87,
  "rev-grip-1": 4.6,
  "rev-pommel": 0.95,
  "rev-switch": 4.76,
  "ridged-extension": 1.9,
  "rogue-grip": 3.8,
  "ronin-extension-emitter": 2.7,
  "ronin-scabbard-sheath-2-0": 1,
  "ronin-sheath-scabbard": 1,
  "ronin-tsuba": 0.7,
  "rook-emitter": 3.8,
  "rook-grip": 4.25,
  "rook-pommel": 0.98,
  "rook-switch-usb-c": 2,
  "rouge-emitter-switch": 6.8,
  "sentinel-emitter": 3.15,
  "sentinel-handle": 4.26,
  "sentinel-pommel": 1.36,
  "sidewinder-2-extension": 2,
  "sidewinder-grip": 3.75,
  "siege-emitter": 2.21,
  "siege-pommel": 0.98,
  "siege-switch": 3.54,
  "single-wing-fallen-ember-shroud": 2.35,
  "slicer-emitter": 3.4,
  "slicer-grip": 4.25,
  "smallmaul-body": 7.2,
  "smallmaul-double-male-coupler-inventory": 1.57,
  "smallmaul-emitter": 1.97,
  "socket-emitter-switch-combo": 5,
  "solaris-booster-extension": 1.18,
  "solaris-choke": 1.38,
  "solaris-emitter": 1.97,
  "solaris-grip-extension": 3.25,
  "solaris-pommel": 1,
  "solaris-switch": 1.95,
  "speeder-extension": 2.7,
  "spire-2-0-emitter": 1.95,
  "spire-pommel": 1.96,
  "switch-grip-extension": 2.76,
  "tavros-pommel": 0.78,
  "tavros-thin-neck-emitter-set": 4.5,
  "tempest-emitter-segment": 1.18,
  "tempest-extension": 2.55,
  "tempest-pommel": 0,
  "temple-shroud": 3.8,
  "the-claw-emitter-switch-combo": 5.1,
  "thin-neck-adapter-set": 1.9,
  "throttle-grip": 4.33,
  "thruster-grip": 6.5,
  "thruster-pommel": 0.62,
  "thruster-switch-emitter-solid-combo": 4.73,
  "titan-emitter": 4.58,
  "titan-pommel": 1.47,
  "titan-switch-grip-combo": 6.6,
  "tonfa-extension": 1.97,
  "torch-emitter": 3.47,
  "torch-grip": 3.95,
  "torch-pommel": 1.17,
  "trencher-pommel": 0.74,
  "tribal-pommel": 0.59,
  "trident-emitter-switch-solid-combo": 4.6,
  "trident-grip": 4.92,
  "trident-pommel": 0.59,
  "type-c-sentinel-2-0-switch": 2,
  "veil-double-connector-pommel": 1,
  "veil-emitter-segment": 1.2,
  "veil-switch-grip": 7.8,
  "vhc-band": 0.65,
  "vhc-cap": 0.28,
  "vhc-choke": 1.25,
  "vhc-curve": 1.4,
  "viper-pommel": 1.28,
  "viper-switch-grip-combo": 5.76,
  "vire-tsuba": 0.34,
  "void-grip": 4.73,
  "void-pommel": 0.59,
  "vortex-grip": 4.25,
  "warden-pommel": 1.17,
  "whirlwind-emitter": 2.75,
  "wren-shroud": 2.25,
  "zenith-emitter": 3.15,
  "zenith-pommel": 0.6,
};

export const LENGTH_BY_TITLE = {
  "1\" day blade - baselit": 36,
  "7/8\" standard blade  - baselit": 1,
  "admiral emitter": 3.1,
  "admiral grip": 4.25,
  "android emitter/switch combo": 5.17,
  "android grip": 4.91,
  "apoc emitter / switch solid combo": 5.15,
  "apoc grip": 4.92,
  "apoc pommel": 0.74,
  "aussabers emitter cap (v1)": 0.4,
  "aussabers incendius double female coupler": 1.57,
  "aussabers invictus pommel": 0.94,
  "aussabers modular crystal chamber": 2.3,
  "aussabers pixel thin neck adapter": 1,
  "ausvire  vhc thin neck set": 1.9,
  "ausvire jade grip": 4.93,
  "ausvire jade grip (scratch & dent)": 4.93,
  "av-wan emitter segment": 1.44,
  "avatar band": 1,
  "avatar emitter segment": 1,
  "banded vhc accent extension": 7,
  "baselit single led cross-blade switch": 4.78,
  "beacon emitter": 3.07,
  "beacon pommel": 1.15,
  "beacon switch (upside down threads!)": 2.87,
  "bermuda emitter": 5.08,
  "bermuda grip": 3.94,
  "bermuda switch (usb-c)": 1.96,
  "bishop emitter": 3.4,
  "bishop grip": 3.8,
  "capsule pommel": 1.8,
  "castille pommel": 1,
  "claw grip": 4.6,
  "claw sphere pommel": 1.13,
  "clutch emitter/switch solid combo": 4.6,
  "clutch grip": 4.32,
  "consular grip": 4.69,
  "consular pommel": 1.77,
  "consular shroud": 2.35,
  "consular switch": 3.03,
  "convergence switch": 2.36,
  "crossguard switch": 3.4,
  "crown emitter": 3.8,
  "cyborg emitter": 3.15,
  "cyborg grip": 4.92,
  "cyborg switch": 2.3,
  "danger noodle (light whip)": 44.5,
  "dark crystal chamber": 3.39,
  "dark rev emitter/switch combo": 6,
  "dark rev grip": 4.46,
  "dark rev pommel": 0.93,
  "darkthorn emitter": 3.82,
  "darkthorn pommel": 1.2,
  "diamondback emitter": 4.3,
  "diamondback jr emitter": 3.27,
  "disk pommel": 0.32,
  "double female coupler": 0.66,
  "double male coupler": 0.38,
  "durendal emitter": 2.42,
  "durendal extension": 3.48,
  "durendal pommel": 1.28,
  "durendal switch": 2.85,
  "equinox emitter": 3.1,
  "etched vire tsuba": 0.35,
  "executioner emitter / switch": 6.8,
  "executioner grip": 3.74,
  "executioner pommel": 0.96,
  "executioner shroud / sleeve": 5.58,
  "extension 1.5\"": 1.5,
  "extension 2\"": 2,
  "fallen ember / consular emitter": 3.26,
  "fallen ember grip": 4.93,
  "fallen ember pommel": 1.73,
  "fallen ember shroud": 4.19,
  "fallen ember switch": 2.83,
  "fang emitter": 3.4,
  "fang grip": 4.2,
  "gatekeeper emitter": 4.1,
  "gill extension": 1,
  "grappler grip with covertec wheel": 5.1,
  "grappler pommel - d-ring": 0.32,
  "grip sleeves": 5.1,
  "guardian double connector pommel": 0.58,
  "guardian emitter": 3.1,
  "guardian grip": 4.21,
  "guardian switch": 2,
  "halcyon choke": 1.7,
  "halcyon emitter": 2.17,
  "halcyon pommel": 1.84,
  "halcyon switch": 5.08,
  "heavy blade": 1,
  "helix emitter": 3.34,
  "helix grip": 3.92,
  "helix pommel": 1.17,
  "helix switch": 2.36,
  "imperial extension": 3.01,
  "imperial pommel": 2.41,
  "infiltrator emitter": 3.03,
  "infiltrator pommel": 1.5,
  "infiltrator switch grip": 6.2,
  "inquisitor grip": 4.86,
  "interceptor emitter / switch": 5.17,
  "interceptor grip": 4.73,
  "interceptor pommel": 0.81,
  "ion grip": 4.93,
  "ion pommel": 1,
  "jester emitter": 3.8,
  "kam extension 2.5\"": 2.55,
  "kam pommel": 1.17,
  "knight emitter": 4.2,
  "lotus emitter": 3.12,
  "lotus grip": 4.9,
  "lotus pommel": 1.13,
  "mantis emitter / switch combo (usb-c)": 6.5,
  "mantis emitter segment": 2.72,
  "mantis grip": 5.5,
  "maul shroud": 2,
  "menace emitter": 2.7,
  "menace pommel": 1.5,
  "menace switch / grip combo": 7.2,
  "mentor grip": 4.9,
  "mentor switch (double male threads)": 2.3,
  "monarch emitter": 3,
  "monarch pommel": 1.1,
  "nostalgia blade (collapsible)  - baselit": 13,
  "nova emitter / switch": 5.06,
  "nova grip": 5.11,
  "nova pommel": 0.88,
  "octo grip": 4.12,
  "odyssey emitter": 2.51,
  "odyssey grip": 4.33,
  "odyssey pommel": 0.99,
  "oracle emitter": 3.69,
  "oracle grip": 4.3,
  "oracle pommel": 1.3,
  "oracle switch": 2.44,
  "oracle switch (type-c mod)": 2.44,
  "padawan grip": 4.3,
  "pathfinder switch/ emitter solid combo": 5.16,
  "pax emitter segment": 1.2,
  "pax pommel": 0.82,
  "phantom grip": 4.9,
  "phoenix emitter": 4.1,
  "phoenix grip": 3.82,
  "phoenix pommel": 1.76,
  "pike grip": 52,
  "pilot emitter": 2.55,
  "pilot grip": 4.33,
  "pilot pommel": 0.62,
  "pixel to base-lit rgb adapter puck": 0.55,
  "raider emitter": 2.56,
  "raider grip": 4.13,
  "raider pommel": 0.98,
  "ranger extension": 3.54,
  "rev double male coupler": 0.87,
  "rev grip": 4.6,
  "rev pommel": 0.95,
  "rev switch": 4.76,
  "rev vhc cap": 0.28,
  "ridged extension": 1.9,
  "rogue emitter/switch usb-c": 6.8,
  "rogue grip": 3.8,
  "ronin extension/ emitter": 2.7,
  "ronin scabbard / sheath": 1,
  "ronin scabbard / sheath 2.0": 1,
  "ronin tsuba only": 0.7,
  "rook emitter": 3.8,
  "rook grip": 4.25,
  "rook pommel": 0.98,
  "rook switch (usb-c)": 2,
  "sentinel emitter": 3.15,
  "sentinel grip": 4.26,
  "sentinel pommel": 1.36,
  "sentinel switch": 2,
  "sidewinder 2\" extension": 2,
  "sidewinder grip": 3.75,
  "siege emitter": 2.21,
  "siege extension (double male)": 2.76,
  "siege pommel": 0.98,
  "siege switch": 3.54,
  "single-wing fallen ember shroud": 2.35,
  "slicer emitter": 3.4,
  "slicer grip": 4.25,
  "small maul double male coupler": 1.57,
  "smallmaul body": 7.2,
  "smallmaul emitter": 1.97,
  "socket emitter/switch solid combo": 5,
  "solaris booster extension": 1.18,
  "solaris choke": 1.38,
  "solaris emitter": 1.97,
  "solaris grip extension": 3.25,
  "solaris pommel": 1,
  "solaris switch": 1.95,
  "speeder extension": 2.7,
  "speeder grip": 4.46,
  "spire emitter": 1.95,
  "spire pommel": 1.96,
  "stealth adapter - female to male vhc thread (double male coupler)": 0,
  "tavros pommel": 0.78,
  "tavros thin neck emitter set": 4.5,
  "tempest emitter segment": 1.18,
  "tempest extension": 2.55,
  "tempest pommel": 0,
  "temple shroud": 3.8,
  "the claw emitter/switch combo": 5.1,
  "throttle grip": 4.33,
  "thruster grip": 6.5,
  "thruster pommel": 0.62,
  "thruster switch/ emitter solid combo": 4.73,
  "titan emitter": 4.58,
  "titan pommel": 1.47,
  "titan switch / grip combo": 6.6,
  "tonfa 2\" extension": 1.97,
  "torch emitter": 3.47,
  "torch grip": 3.95,
  "torch pommel": 1.17,
  "trencher pommel": 0.74,
  "tribal pommel": 0.59,
  "trident emitter/switch solid combo": 4.6,
  "trident grip": 4.92,
  "trident pommel": 0.59,
  "veil double connector pommel": 1,
  "veil emitter segment": 1.2,
  "veil switch grip": 7.8,
  "vhc band": 0.65,
  "vhc choke": 1.25,
  "vhc curve": 1.4,
  "viper pommel": 1.28,
  "viper switch  grip": 5.76,
  "vire mini tsuba": 0.59,
  "vire tsuba": 0.34,
  "void grip": 4.73,
  "void pommel": 0.59,
  "vortex grip": 4.25,
  "warden pommel": 1.17,
  "whirlwind emitter": 2.75,
  "wren shroud": 2.25,
  "zenith emitter": 3.15,
  "zenith pommel": 0.6,
};

function slugFromPart(part) {
  if (!part) return "";
  const url = part.url || "";
  const m = url.match(/\/products\/([^/?#]+)/);
  if (m) return m[1];
  return part.id || "";
}

export function partLengthAdded(part) {
  if (!part) return 0;
  const slug = slugFromPart(part);
  if (slug && LENGTH_BY_SLUG[slug] != null) return LENGTH_BY_SLUG[slug];
  const title = (part.title || "").trim().toLowerCase();
  if (title && LENGTH_BY_TITLE[title] != null) return LENGTH_BY_TITLE[title];
  return 0;
}

export function hiltLengthInches(build, second, staffOn) {
  let total = 0;
  for (const slot of ["emitter", "switch", "grip", "pommel"]) {
    total += partLengthAdded(build?.[slot]);
  }
  for (const extra of build?.extras || []) {
    if (extra.slot === "vhc") total += partLengthAdded(extra.part);
  }
  if (staffOn && second) {
    for (const slot of ["emitter", "switch", "grip"]) {
      total += partLengthAdded(second[slot]);
    }
    for (const extra of second.extras || []) {
      if (extra.slot === "vhc") total += partLengthAdded(extra.part);
    }
  }
  return total;
}

export function formatHiltLength(inches) {
  if (!inches) return '0.00"';
  const n = Math.round(inches * 100) / 100;
  const s = n.toFixed(2).replace(/0+$/, "").replace(/\.$/, "");
  return s + '"';
}
